#spring.application.name=swim
spring:
  thymeleaf:
#    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    check-template-location: true
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8383